spring.application.name=ojpms

spring.datasource.url=jdbc:postgresql://localhost:5432/ojpms
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp

server.port=${PORT:8080}
